# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"

    default_config: user_config
    configs:
        user_config:
            toolbar: [ ["Bold", "Italic", "Underline", "-", "NumberedList", "BulletedList" ] ]
            removePlugins: 'elementspath'
            # uiColor: "#66AB16"
            extraPlugins: ['justify', 'font']
            height: 100
        
        admin_config:
            extraPlugins: ['justify', 'font']
            removePlugins: 'elementspath'
            toolbar: [ ["Bold", "Italic", "-", "NumberedList", "BulletedList", "-", "JustifyLeft", 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Link', 'Unlink'], "-", ["Format", 'TextColor', 'BGColor', "Maximize"], "/", ["Font", 'FontSize', 'Image', '-', "Source"] ]

        raw_config:
            extraPlugins: ['justify', 'font']
            removePlugins: 'elementspath'
            toolbar: [ ["Bold", "Italic", "-", "NumberedList", "BulletedList", "-", "JustifyLeft", 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Link', 'Unlink'], "-", ["Format", 'TextColor', 'BGColor', "Maximize"], "/", ["Font", 'FontSize', 'Image', '-', "Source"] ]
            enterMode: CKEDITOR.ENTER_BR
            allowedContent: true